### ISSUE TITLE
Sharp Install Issue

### ISSUE THREAD

**Issue by Scott123180** [scttcper/gatsby-casper#61]
Issue installing sharp dependencies - tried suggested mitigation on gatsby site (delete `node_modules` and re-install)
https://www.gatsbyjs.org/docs/troubleshooting-common-errors/#problems-installing-sharp-with-gatsby-plugin-sharp---gyp-err-build-error

sharp build-from-source fails because of libvips library compatibility with latest node version

upgrading versions of sharp and sharp-transform have fixed this issue for me

ERRORS below

``` bash
npm@6.13.7 /home/scott/.nvm/versions/node/v13.11.0/lib/node_modules/npm

> sharp@0.22.1 install /home/scott/Documents/coding/open-source/gatsby-casper/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/scott/.npm/_libvips/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=13.11.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/scott/Documents/coding/open-source/gatsby-casper/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
         channels->Set(i, channelStat);
                                     ^
In file included from /home/scott/.cache/node-gyp/13.11.0/include/node/node.h:67:0,
                 from ../src/stats.cc:19:
/home/scott/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/scott/.cache/node-gyp/13.11.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/scott/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/scott/.cache/node-gyp/13.11.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:138: recipe for target 'Release/obj.target/sharp/src/stats.o' failed
make: *** [Release/obj.target/sharp/src/stats.o] Error 1
make: Leaving directory '/home/scott/Documents/coding/open-source/gatsby-casper/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/scott/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-42-generic
gyp ERR! command "/home/scott/.nvm/versions/node/v13.11.0/bin/node" "/home/scott/.nvm/versions/node/v13.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/scott/Documents/coding/open-source/gatsby-casper/node_modules/sharp
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scott/.npm/_logs/2020-03-21T15_46_25_225Z-debug.log

```

**Comment by Confidenceiskey** [comment]
Just to elaborate on the above issue....as the same thing (error message) happened to me just now. 

Since I couldn't find the latest version numbers for the packages, I modified the two values (shown below) within the `package.json` file. 

`"gatsby-plugin-sharp": "^2.2.9"`
`"gatsby-transformer-sharp": "^2.2.4"`

Then ran `yarn` (or `npm install`) and it fixed the issue. It is basically just adding the caret `^` symbol, and really don't understand why none of the listed packages have this...

**Comment by scttcper** [comment]
Pinned packages do tend to work better when they're frequently updated. Node 13 didn't exist back when they were pinned. I've added an nvmrc in the next version https://github.com/scttcper/gatsby-casper/pull/64 and node 13 should be supported
